# Generated by Django 3.2.20 on 2023-09-15 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=20)),
                ('images', models.ImageField(upload_to='member_face')),
                ('studyday_type', models.CharField(choices=[('火曜１７時', '火曜１７時'), ('火曜１８時', '火曜１８時'), ('水曜１７時', '水曜１７時'), ('水曜１８時', '水曜１８時'), ('金曜１７時', '金曜１７時'), ('金曜１８時', '金曜１８時'), ('土曜１０時', '土曜１０時'), ('土曜１１時', '土曜１１時'), ('土曜１３時', '土曜１３時'), ('土曜１４時', '土曜１４時')], max_length=10)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.post')),
            ],
        ),
    ]
