# Generated by Django 3.2.20 on 2023-09-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='save',
            field=models.BooleanField(default=False),
        ),
    ]
