# Generated by Django 3.2.20 on 2023-09-07 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20230907_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='post',
            name='school',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
