# Generated by Django 3.2.20 on 2023-09-07 16:25

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20230908_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='created_date',
        ),
        migrations.AddField(
            model_name='post',
            name='studyday_type',
            field=blog.models.ChoiceField(choices=[('option1', 'Option 1'), ('option2', 'Option 2'), ('option3', 'Option 3'), ('option4', 'Option 4'), ('option5', 'Option 5'), ('option6', 'Option 6'), ('option7', 'Option 7'), ('option8', 'Option 8'), ('option9', 'Option 9'), ('option10', 'Option 10')], default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='school',
            field=models.CharField(max_length=20),
        ),
    ]
