# Generated by Django 3.2.20 on 2023-09-07 16:27

import blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20230908_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='studyday_type',
            field=blog.models.ChoiceField(choices=[('option1', '火曜１７時'), ('option2', '火曜１８時'), ('option3', '水曜１７時'), ('option4', '水曜１８時'), ('option5', '金曜１７時'), ('option6', '金曜１８時'), ('option7', '土曜１０時'), ('option8', '土曜１１時'), ('option9', '土曜１３時'), ('option10', '土曜１４時')], max_length=20),
        ),
    ]
