# Generated by Django 3.2.20 on 2023-09-16 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_save'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='save',
            new_name='savepoint',
        ),
    ]
