# Generated by Django 3.2.20 on 2023-09-07 16:32

import blog.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_post_studyday_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='studyday_type',
            field=blog.models.ChoiceField(choices=[('火曜１７時', '火曜１７時'), ('火曜１８時', '火曜１８時'), ('水曜１７時', '水曜１７時'), ('水曜１８時', '水曜１８時'), ('金曜１７時', '金曜１７時'), ('金曜１８時', '金曜１８時'), ('土曜１０時', '土曜１０時'), ('土曜１１時', '土曜１１時'), ('土曜１３時', '土曜１３時'), ('土曜１４時', '土曜１４時')], max_length=20),
        ),
    ]
