# Generated by Django 3.2.20 on 2023-09-17 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20230917_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to="{% uplode_image 'contact_image' %}"),
        ),
    ]
