# Generated by Django 3.2.20 on 2023-09-08 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_post_studyday_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='images',
            field=models.ImageField(default=1, upload_to='./static/image/menber_face'),
            preserve_default=False,
        ),
    ]
