# Generated by Django 3.2.20 on 2023-09-17 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20230918_0155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='images',
            field=models.ImageField(upload_to='member_face'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.ImageField(default=1, upload_to='contact_image'),
            preserve_default=False,
        ),
    ]
