# Generated by Django 4.2.2 on 2023-09-26 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20230918_0308'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='katakana',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
