# Generated by Django 4.2.2 on 2023-09-26 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_alter_post_studyday_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='savepoint',
            field=models.CharField(choices=[('not save', 'not save'), ('save', 'save')], default='not save', max_length=10),
        ),
        migrations.AlterField(
            model_name='post',
            name='studyday_type',
            field=models.CharField(choices=[('火曜１７時', '火曜１７時'), ('火曜１８時', '火曜１８時'), ('水曜１７時', '水曜１７時'), ('水曜１８時', '水曜１８時'), ('金曜１７時', '金曜１７時'), ('金曜１８時', '金曜１８時'), ('土曜１０時', '土曜１０時'), ('土曜１１時', '土曜１１時'), ('土曜１３時', '土曜１３時'), ('土曜１４時', '土曜１４時')], max_length=10),
        ),
    ]
