# Generated by Django 3.2.20 on 2023-09-28 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
        migrations.AddField(
            model_name='account',
            name='images',
            field=models.ImageField(default='./static/image/logo/barbershop.png', upload_to='member_face'),
        ),
        migrations.AddField(
            model_name='account',
            name='katakana',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='school',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='studyday_type',
            field=models.CharField(choices=[('Tuesday 17:00', 'Tuesday 17:00'), ('Tuesday 18:00', 'Tuesday 18:00'), ('Wednesday 17:00', 'Wednesday 17:00'), ('Wednesday 18:00', 'Wednesday 18:00'), ('Friday 17:00', 'Friday 17:00'), ('Friday 18:00', 'Friday 18:00'), ('Saturday 10:00', 'Saturday 10:00'), ('Saturday 11:00', 'Saturday 11:00'), ('Saturday 13:00', 'Saturday 13:00'), ('Saturday 14:00', 'Saturday 14:00')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment', to='blog.account'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
