# Generated by Django 3.2.20 on 2023-09-28 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0019_auto_20230928_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='images',
        ),
        migrations.RemoveField(
            model_name='account',
            name='katakana',
        ),
        migrations.RemoveField(
            model_name='account',
            name='name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='account',
            name='school',
        ),
        migrations.RemoveField(
            model_name='account',
            name='studyday_type',
        ),
        migrations.AddField(
            model_name='account',
            name='first_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='last_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('katakana', models.CharField(max_length=200)),
                ('school', models.CharField(max_length=20)),
                ('images', models.ImageField(upload_to='member_face')),
                ('studyday_type', models.CharField(choices=[('Tuesday 17:00', 'Tuesday 17:00'), ('Tuesday 18:00', 'Tuesday 18:00'), ('Wednesday 17:00', 'Wednesday 17:00'), ('Wednesday 18:00', 'Wednesday 18:00'), ('Friday 17:00', 'Friday 17:00'), ('Friday 18:00', 'Friday 18:00'), ('Saturday 10:00', 'Saturday 10:00'), ('Saturday 11:00', 'Saturday 11:00'), ('Saturday 13:00', 'Saturday 13:00'), ('Saturday 14:00', 'Saturday 14:00')], max_length=100)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Comment', to='blog.post'),
        ),
    ]
