# Generated by Django 3.2.20 on 2023-09-28 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20230928_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='userid',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
