# Generated by Django 3.2.20 on 2023-09-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_post_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='userid',
            field=models.IntegerField(max_length=10),
        ),
    ]
