# Generated by Django 3.2.20 on 2023-09-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_alter_post_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='userid',
            field=models.CharField(max_length=200),
        ),
    ]
